# Generated by Django 3.1.1 on 2020-09-28 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=500)),
                ('date', models.CharField(blank=True, default='28/09/2020 13:44:51', max_length=1000)),
            ],
        ),
    ]
